In [ ]:
# Neil Arora - 25070123080
# Experiment 10 - Study of Panda Library in Python

In [1]:
import pandas as pd
s=pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
# Create Dataframe
data={"Name":["A","B","C"],
      "Marks":[85,90,78]}
df=pd.DataFrame(data)
df

  Name  Marks
0    A     85
1    B     90
2    C     78

In [ ]:
df.head()
df.tail()

In [7]:
# Find the structure of the DataFrame
print(df.shape)
print(df.ndim)
print(df.size)
# Display Column names
print(df.columns)

(3, 2)
2
6
Index(['Name', 'Marks'], dtype='object')

In [8]:
# Check Data Types of Each Column
print(df.dtypes)

Name     object
Marks     int64
dtype: object

In [9]:
# Acess Individual Columns
df["Name"]

0    A
1    B
2    C
Name: Name, dtype: object

In [12]:
# Access Name of first row
print(df.loc[0,"Name"])
print(df.iloc[2,1])

A
78

In [14]:
# Add a New Column
df["Grade"]=["First Class","Distinction","Second Class"]
print(df)

  Name  Marks         Grade
0    A     85   First Class
1    B     90   Distinction
2    C     78  Second Class

In [16]:
# Update Data in DataFrame
# Change marks of Student A to be 88
df.iloc[0,1]=88
print(df)

  Name  Marks         Grade
0    A     88   First Class
1    B     90   Distinction
2    C     78  Second Class

In [21]:
# Delete Column
df1=df.drop("Grade",axis=1)
print(df)
print(df1)

  Name  Marks         Grade
0    A     88   First Class
1    B     90   Distinction
2    C     78  Second Class
  Name  Marks
0    A     88
1    B     90
2    C     78

In [22]:
# Perfrom Basic Statistical Analysis
mean1=df["Marks"].mean()
print(mean1)
min1=df["Marks"].min()
max1=df["Marks"].max()
print(min1)
print(max1)

85.33333333333333
78
90

In [24]:
# Filtering
df[df["Marks"]>80]

  Name  Marks        Grade
0    A     88  First Class
1    B     90  Distinction